BEGIN;

DROP TABLE IF EXISTS "liste", "carte", "label", "carte_has_label";


CREATE TABLE IF NOT EXISTS "liste" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "nom" varchar(255) NOT NULL,
    "position" integer NOT NULL UNIQUE,   
    "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" timestamptz
);

CREATE TABLE IF NOT EXISTS "carte" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "contenu" text NOT NULL,
    "position" integer NOT NULL UNIQUE,
    "couleur" varchar(7),
    "liste_id" integer NOT NULL references "liste" ("id"),
    "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" timestamptz
);

CREATE TABLE IF NOT EXISTS "label" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "nom" varchar(255) NOT NULL UNIQUE,
    "couleur" varchar(7) NOT NULL,
    "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" timestamptz
);

CREATE TABLE IF NOT EXISTS "carte_has_label" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "carte_id" integer NOT NULL REFERENCES "carte" ("id"),
    "label_id" integer NOT NULL REFERENCES "label" ("id"),    
    "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" timestamptz
);

COMMIT;

