@endpoint = http://localhost:5002/api

############ LISTS ##########

### Get all lists
GET {{endpoint}}/lists


### Get one list
GET {{endpoint}}/lists/1

### Create list
POST {{endpoint}}/lists
Content-Type: application/x-www-form-urlencoded

name=Nouvelle liste
&position=42


############ CARDS ##########

GET {{endpoint}}/cards

###

GET {{endpoint}}/cards/3/position/18

###

GET {{endpoint}}/tags/2



############ MISC ##########

GET {{endpoint}}/404

###

POST {{endpoint}}/cards
Content-Type: application/json

{
    "content": "test1",
    "position": 6,
    "color": "test",
    "list_id": 1
}